---
apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-app-config
  namespace: vk67220-ns
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-headless:5432/employees
  POSTGRES_DB: employees
---
