---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
  namespace: vk67220-ns
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: employee-app 
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-app-container
          image: prasad5806/springboot-postgresql-hibernate-crud-example-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: employee-app-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: employee-app-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-app-secret
                  key: SPRING_DATASOURCE_PASSWORD
---
